-- Rollback : restaurer le format OLD pour les 13 questions migrées par 20260527e_migrate_matching_old_to_new.sql.
-- Source : docs/migrations/20260527_matching_old_format_backup.csv (snapshot pré-migration).
--
-- Étapes :
-- 1. Drop la contrainte CHECK qui bloquerait la restauration.
-- 2. UPDATE individuel par id (13 lignes) avec le JSON original.
-- 3. Pas de re-création de contrainte : ce down restaure l'état mixed OLD+NEW d'avant migration.

ALTER TABLE questions DROP CONSTRAINT IF EXISTS matching_new_format_only;

UPDATE questions SET options = '{"pairs": [{"id": "1", "left": "Icon-Etch (Acide chlorhydrique 15%)", "right": "Crée des microporosités pour ouvrir l''accès à la lésion"}, {"id": "2", "left": "Icon-Dry (Éthanol)", "right": "Simule le résultat final et déshydrate la lésion"}, {"id": "3", "left": "Icon-Infiltrant (Résine fluide)", "right": "Infiltre par capillarité les porosités de l''émail"}]}'::jsonb WHERE id = '07c7b6a6-f0f0-419d-a9c3-59e5e1f41636';

UPDATE questions SET options = '{"pairs": [{"left": "1 à 2 ans", "right": "Privilégier un contact sécurisant en présence permanente des parents et anticiper la peur face à tout élément nouveau."}, {"left": "2 à 4 ans", "right": "Contourner la période d''opposition en privilégiant massivement les gestes et les images, la communication verbale étant insuffisante."}, {"left": "4 à 6 ans", "right": "Utiliser la méthode Dire-Montrer-Faire et stimuler l''imaginaire, car la notion du temps et de l''espace est encore très restreinte."}, {"left": "6 à 11 ans", "right": "Cadrer avec fermeté et bienveillance face à une potentielle indiscipline liée à la scolarisation et la recherche d''indépendance."}]}'::jsonb WHERE id = '094290d2-7a27-4a82-8bb3-24461a76ee72';

UPDATE questions SET options = '{"pairs": [{"id": "1", "left": "Stade 1", "right": "Coiffe neigeuse limitée au sommet des cuspides"}, {"id": "2", "left": "Stade 3", "right": "Aspect en parchemin blanc sur au moins 2/3 de la surface"}, {"id": "3", "left": "Stade 4", "right": "Plages de coloration marron clair à foncé"}, {"id": "4", "left": "Stade 5", "right": "Piqueté discret avec coloration possible"}]}'::jsonb WHERE id = '391d2a85-d93e-41a3-a9bb-cd1629ef26ad';

UPDATE questions SET options = '{"pairs": [{"id": "1", "left": "Black stains", "right": "Bactéries Actinomyces"}, {"id": "2", "left": "Colorations brun foncé", "right": "Tanins"}, {"id": "3", "left": "Bandes vertes adhérentes", "right": "Champignons (Penicillium)"}, {"id": "4", "left": "Dépôts brunâtres peu adhérents", "right": "Chlorhexidine"}]}'::jsonb WHERE id = '3ba615c3-7de6-4a4f-87f3-99dbe5c90eaa';

UPDATE questions SET options = '{"pairs": [{"left": "Afficher sur son site web une sélection de témoignages positifs de patients satisfaits de leur sourire.", "right": "Strictement interdit par l''article R.4127-215-1 : interdiction de faire appel à des témoignages de tiers."}, {"left": "Envoyer le dossier médical d''un patient à un confrère spécialiste via une adresse email non cryptée (Gmail).", "right": "Interdit par l''article R.4127-208 et le RGPD : défaut de protection des données informatiques sensibles."}, {"left": "Répondre à un avis Google négatif par un message type demandant au patient de contacter le secrétariat.", "right": "Pratique conforme au cadre déontologique, permettant de préserver son e-réputation tout en respectant le secret médical."}, {"left": "Payer pour une campagne Google Ads afin que le cabinet apparaisse en premier lors d''une recherche « Urgence dentiste ».", "right": "Strictement interdit par l''article R.4127-217 : interdiction du référencement numérique payant prioritaire."}]}'::jsonb WHERE id = '4206690d-d52f-4954-b241-2b5cd0919471';

UPDATE questions SET options = '{"pairs": [{"id": "1", "left": "Dommage sévère, structure affaiblie", "right": "Couronne"}, {"id": "2", "left": "Dommage modéré, parois saines", "right": "Onlay"}, {"id": "3", "left": "Carie interproximale limitée", "right": "Obturation directe"}, {"id": "4", "left": "Recouvrement complet de toutes les cuspides", "right": "Overlay"}]}'::jsonb WHERE id = '518dddc1-0999-4e04-b4a1-32f80cadbcfa';

UPDATE questions SET options = '{"pairs": [{"left": "Handicap moteur (Paralysie Cérébrale / IMC)", "right": "Éviter d''imposer une position standard ; accompagner les mouvements spastiques sans les bloquer ; traiter dans le fauteuil roulant si le transfert est impossible."}, {"left": "Handicap sensoriel auditif (Sourd / Malentendant)", "right": "Retirer son masque pour la lecture labiale, bien éclairer son visage, et éteindre les prothèses auditives avant d''utiliser la turbine pour éviter l''effet Larsen."}, {"left": "Handicap sensoriel visuel (Aveugle / Malvoyant)", "right": "Annoncer verbalement chaque étape avant de toucher le patient, utiliser le retour tactile (main sur l''épaule), et décrire précisément les sensations à venir."}, {"left": "Handicap cognitif (TSA / Trisomie 21)", "right": "Minimiser l''environnement sensoriel, utiliser un langage littéral sans métaphores, et s''appuyer sur la méthode Dire-Montrer-Faire couplée à des pictogrammes."}]}'::jsonb WHERE id = '8cc428fa-6a3c-4ad8-a2d7-def041014848';

UPDATE questions SET options = '{"pairs": [{"left": "Patient expert", "right": "Ne pas rejeter ses recherches, les corriger avec respect et l''impliquer dans la décision médicale partagée."}, {"left": "Patient passif", "right": "Stimuler son implication par des questions ouvertes et vérifier la compréhension avec le Teach-back."}, {"left": "Patient anxieux", "right": "Structurer la séance avec la méthode Dire-Montrer-Faire et instaurer un signal d''arrêt clair."}, {"left": "Patient méfiant", "right": "Ne pas se défendre agressivement ; utiliser la transparence et la preuve par l''image (caméra intra-orale, radiographies)."}]}'::jsonb WHERE id = 'b55bd84f-b8dc-4285-8d24-0de137511594';

UPDATE questions SET options = '{"pairs": [{"id": "1", "left": "Amélogenèse imparfaite", "right": "Émail / Contraste émail-dentine faible ou normal"}, {"id": "2", "left": "Dentinogenèse imparfaite", "right": "Dentine / Oblitération pulpaire"}, {"id": "3", "left": "Dysplasie dentinaire type II", "right": "Dentine / Chambres pulpaires très larges (en chardon)"}]}'::jsonb WHERE id = 'ef47e86e-2dd2-49be-a0fe-4987de65d205';

UPDATE questions SET options = '{"pairs": [{"id": "1", "left": "Sensibilités faibles apparaissant au 2ème jour", "right": "Passage à un dentifrice désensibilisant"}, {"id": "2", "left": "Sensibilités préexistantes importantes", "right": "Pré-traitement de 15 jours au nitrate de potassium"}, {"id": "3", "left": "Sensibilités modérées mais systématiques au 4ème jour", "right": "Pause d''un jour entre les applications, avec gel de KNO3"}, {"id": "4", "left": "Sensibilités intenses et imprévisibles", "right": "Recherche du seuil individuel de temps de port"}]}'::jsonb WHERE id = 'f07f4975-dd6a-4bef-b3ca-f8255fa8ea2c';

UPDATE questions SET options = '{"pairs": [{"id": "1", "left": "Craze line", "right": "Excellent (asymptomatique)"}, {"id": "2", "left": "Fractured cusp", "right": "Bon"}, {"id": "3", "left": "Cracked tooth (sans atteinte pulpaire)", "right": "Variable selon profondeur"}, {"id": "4", "left": "Split tooth", "right": "Mauvais à désespéré"}]}'::jsonb WHERE id = 'f2ff7518-c2cf-421d-9116-652c2e73f5a3';

UPDATE questions SET options = '{"pairs": [{"id": "1", "left": "Disilicate de Lithium", "right": "Fracture/Ébréchure (\"chipping\")"}, {"id": "2", "left": "Composite CAD/CAM", "right": "Décoloration marginale et perte de brillant"}, {"id": "3", "left": "Zircone Monolithique", "right": "Usure de la dent antagoniste"}, {"id": "4", "left": "Céramo-métallique", "right": "Fracture du cosmétique (céramique)"}]}'::jsonb WHERE id = 'f5a693f6-443e-45c2-895c-8e64572bf27f';

UPDATE questions SET options = '{"pairs": [{"left": "Promotion de l''hygiène bucco-dentaire", "right": "Moins de maladies carieuses et parodontales, donc moins de soins restaurateurs", "rightId": "C"}, {"left": "Groupement des séances de soins", "right": "Moins de déplacements pour les patients", "rightId": "A"}, {"left": "Pertinence des soins", "right": "Moins de consommation de matériel et de production de déchets", "rightId": "B"}, {"left": "Dé-prescription", "right": "Réduction de la consommation de médicaments et de leurs rejets dans l''environnement ", "rightId": "D"}]}'::jsonb WHERE id = 'fd08469b-3bbb-4656-8651-f95a45f28ec3';
